<../../mkconfig

TARG=\
	mercurial.dis\
	mercurialwire.dis\
	mercurialremote.dis\

MODULES=\
	mercurialwire.m\
	mercurialremote.m\

SYSMODULES=\
	mercurial.m\
	sys.m\
	bufio.m\
	daytime.m\
	filter.m\
	keyring.m\
	lists.m\
	string.m\
	util0.m\
	filtertool.m\

DISBIN=$ROOT/dis/lib

<$ROOT/mkfiles/mkdis
