<../../../mkconfig

TARG=\
	delta.dis\
	printpatch.dis\
	printchangegroup.dis\
	testapply.dis\
	printconfig.dis\

SYSMODULES=\
	mercurial.m\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	filter.m\
	keyring.m\
	lists.m\
	string.m\
	styx.m\
	styxservers.m\
	sys.m\
	tables.m\
	filtertool.m\

DISBIN=$ROOT/dis/hg

<$ROOT/mkfiles/mkdis
