<../../../mkconfig


TARG=\
	get.dis\
	tar.dis\
	log.dis\
	fs.dis\
	dirstate.dis\
	status.dis\
	readrevlog.dis\

SYSMODULES=\
	mercurial.m\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	filter.m\
	keyring.m\
	lists.m\
	string.m\
	styx.m\
	styxservers.m\
	sys.m\
	tables.m\

DISBIN=$ROOT/dis/hg

<$ROOT/mkfiles/mkdis
