<../../../mkconfig


TARG=\
	get.dis\
	tar.dis\
	log.dis\
	#readindex.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyring.m\
	string.m\
	sys.m\

DISBIN=$ROOT/dis/hg

<$ROOT/mkfiles/mkdis
